### ISSUE TITLE
Cannot access webite

### ISSUE THREAD

**Issue by knjk04** [Ckbhatia/ck_newsletter#1]
When I go to https://cknewsletter.netlify.app/ (the link that your live button on your [projects page](https://ckportfolio.netlify.app/#projects) points towards), I see a page that says 'Not found' (see the screenshot below).

![image](https://user-images.githubusercontent.com/11173328/85107038-2bf0bf80-b205-11ea-8f49-50353b9ac39d.png)

If it helps, I'm running Firefox 77.0.1 (64-bit) on Windows 10, version 2004.

**Comment by Ckbhatia** [comment]
@knjk04 Thank you for pointing this issue. Let me check.

**Comment by Ckbhatia** [comment]
There's wrong address of this project on portfolio.

Let me fix rhis.

You can visit this: cknewsletter.herokuapp.com

**Comment by Ckbhatia** [comment]
Issue has been resolved.
